# Generated by Django 2.2 on 2021-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0003_auto_20210827_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='static/images/'),
        ),
    ]
