# Generated by Django 2.2 on 2021-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_auto_20210827_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='static/images'),
        ),
    ]
